### ISSUE TITLE
U1: As a user, I want to be able to register an account, so that resources that I own or I can manage will be visible to me.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#1]
## Acceptance Criteria
- [x] Given the user has provided a username and password, when clicking on ‘register’, then a user account is created.
- [x] Given the user has not provided all required data for registration, when clicking ‘register’, the button is disabled and the user account is not created.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#14
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#27
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#28
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#29

### Backend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#24
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#30
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#31
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#35
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#36

**Comment by NorDar** [comment]
- [ ] test

**Comment by NorDar** [comment]
* Provided a username, password and email is provided an account is created and the user logged in
* If partial data is provided the button is grayed out
