### ISSUE TITLE
P9: As a user, I want to upload a photo of my plant, so it is identifiable in the web ui.

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-server#125]
## Acceptance Criteria

- [x] Given a plant exists, it is possible to upload an image for this plant so this can be shown.
- [x] Given a user is logged in and has a plant created, when on the dasboard or the plant overview, this user and other users that have access to this plant can see the plants image.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#69
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#70

### Backend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#128
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#129
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#130

**Comment by NorDar** [comment]
Also: 
#139
