### ISSUE TITLE
S2: As a user, I want to add or remove plants to and from a space, in order to organize them.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#17]
## Acceptance Criteria

- [x] Given a space is created, when on the page of the space the option to add a plant is clicked, the user can either select an existing plant or add a new one. (Plants should not be able to be in more than one space)
- [x] Given plants are added to a space, when the clicks on ‘edit space’ the option to delete plants from the space is displayed.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#64

### Backend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#86
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#87
- [x] #132
- [x] #133
