### ISSUE TITLE
S3: As a user, I want to assign other users to a space, so they can see the schedule of all plants.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#18]
## Acceptance Criteria

- [x] Given a user is logged in and has a space created, when sharing a space, other users also have access to the space and its plants.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#65

### Backend

- [x] #116
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#88
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#89
