### ISSUE TITLE
U2: As a user, I want to be able to log in to the application so that I can benefit from its features.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#2]
## Acceptance Criteria
- [x] Given the user has registered, when giving the correct credentials the user is logged in.
- [x] Given, the user has logged in, the front page is shown.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#30
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#31

### Backend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#40
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#41
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#60

**Comment by NorDar** [comment]
* Given the credentials the user is logged in 
* The front page is shown
