### ISSUE TITLE
U3: As a user, I want to update my profile information, so that I can make sure my details are accurate and up to date.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#3]
## Acceptance Criteria

- [x] Given the user is logged in, when going to the profile, user data is displayed.
- [x] Given the user is at the profile page, when clicking on the edit button, the edit menu is displayed.
- [x] Given the user edited their profile details, when clicking on the update button, then user data is updated and the user is redirected to the profile page.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#49
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#66
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#67

### Backend

- Backend functionality is already implemented for this.
