### ISSUE TITLE
P1: As a plant owner, I want to be able to create plants, so that I can manage them in the application.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#4]
## Acceptance Criteria

- [x] Given the user is logged in, when clicking on the ‘add new plant’ button, then the ‘add plant’ page is displayed.
- [x] Given the user is on the ‘add plant’ page, when filling in the required data, then the ‘add’ button is enabled.
- [x] Given the user has filled out the required data, when clicking the ‘save’ button, a new plant is created and the user is redirected to the main page where all the plants are displayed.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#24
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#25
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#26

### Backend

- [x] #42
- [x] #45
- [x] #46
